-- 01_schema.sql — Neon development 브랜치 SQL Editor에서 전체 실행.
-- Supabase public 스키마 미러. 중복 유니크 인덱스는 1개씩만 생성.

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE public.users (
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    email text NOT NULL,
    name text NOT NULL,
    avatar_url text NOT NULL,
    plan text,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone,
    subscription_id text,
    subscription_current_period_start timestamp with time zone,
    subscription_current_period_end timestamp with time zone,
    image_limit integer,
    last_subscribed_at timestamp with time zone NOT NULL DEFAULT now(),
    scheduled_downgrade_at timestamp with time zone,
    downgrade_target_plan_id text,
    preferred_ai_model_config jsonb,
    fal_ai_api_key text,
    replicate_api_key text,
    CONSTRAINT users_pkey PRIMARY KEY (id)
);

CREATE TABLE public.ad_generation_batches (
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    user_id uuid NOT NULL,
    status text NOT NULL,
    product_image jsonb,
    person_image jsonb,
    brand_logo jsonb,
    aspect_ratios jsonb NOT NULL,
    concept_count integer NOT NULL,
    cta_enabled boolean NOT NULL DEFAULT false,
    brand_palette jsonb,
    ad_creative_specs jsonb NOT NULL DEFAULT '[]'::jsonb,
    ad_creative_results jsonb NOT NULL DEFAULT '[]'::jsonb,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone,
    CONSTRAINT ad_generation_batches_pkey PRIMARY KEY (id)
);

CREATE TABLE public.subscription_grants (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    user_id uuid NOT NULL,
    polar_subscription_id text,
    cycle_start timestamp with time zone NOT NULL,
    cycle_end timestamp with time zone NOT NULL,
    granted integer NOT NULL,
    reason text NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT subscription_grants_pkey PRIMARY KEY (id),
    CONSTRAINT subscription_grants_sub_cycle_reason_key UNIQUE (polar_subscription_id, cycle_start, reason)
);

CREATE UNIQUE INDEX subscription_grants_user_trial_uidx
    ON public.subscription_grants USING btree (user_id)
    WHERE (reason = 'trial'::text);

CREATE TABLE public.usage_ledger (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    user_id uuid NOT NULL,
    batch_id uuid NOT NULL,
    creative_index integer NOT NULL,
    ratio_key text NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT usage_ledger_pkey PRIMARY KEY (id),
    CONSTRAINT usage_ledger_user_batch_creative_ratio_key UNIQUE (user_id, batch_id, creative_index, ratio_key),
    CONSTRAINT usage_ledger_batch_creative_ratio_uidx UNIQUE (batch_id, creative_index, ratio_key)
);

CREATE INDEX usage_ledger_user_created_idx
    ON public.usage_ledger USING btree (user_id, created_at DESC);
